### ISSUE TITLE
[Mary Masako Yamashita][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#100]
### *Mary Masako Yamashita*
*church should be capitalized *

### What We Should Do to Fix it
- [x] *capitalize church*
- [x] copy paste below text

### Copy And Paste-able Text
Mary Yamashita left Rohwer and attended Muskingum College in Ohio with the Quaker Council’s aid earning her degree in English. She married James Doi and moved to occupied Japan. There, Mary joined the civilian economic affairs department. The couple moved to Chicago as James pursued his PhD and later Seattle where Mary advocated for the Buddhist Church and steelworker unions.

**Comment by Prot0ast** [comment]
gtg 👍
