### ISSUE TITLE
[Rohwer, Education, Recreational, Destination Rohwer, Arkansas, Camp Rohwer remains][The orphans and widows]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#101]
### Rohwer, Education, Recreational, Destination Rohwer, Arkansas, Train second visual, Camp Rohwer remains
Rohwer: Activities orphan
Education: crafts orphan
Recreational: time orphan
Destination Rohwer, Arkansas: Rohwer orphan
Train second visual: for sleeping widow
Camp Rohwer remains: new lives widow

### What We Should Do to Fix it
- [x] Remove the first and in Rohwer page
- [x] Crafts orphan, another issue slightly changes it
- [x] time orphan, another issue slightly changes it
- [x] Destination Rohwer, Arkansas  Rohwer orphan. Space after Family. Make text larger?
- [x] Train second visual for sleeping widow. make text larger?
- [x] Camp Rohwer remains new lives widow. Make text larger?

### Copy And Paste-able Text
A large complex of tar-paper buildings including mess halls, barracks, showers, an incomplete school and hospital are surrounded by wire fences.

**Comment by Prot0ast** [comment]
I have saved the orphans
