### ISSUE TITLE
[George Akimoto - Yearbook][text is wrongish]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#102]
### *George Akimoto - Yearbook*
*movie titles aren't italicized and lil dan'l book not italicized*

### What We Should Do to Fix it
- [x] italicize movie names: Silent Running, The Wild Party, and At the Earth's Core
- [x] italicize Lil Dan'l book name

### Copy And Paste-able Text
George Akimoto married Dorothy Yoshiye Kaneshige during his 3rd and final year at Rohwer. The couple moved to Los Angeles where George, a renowned commercial artist, made movie posters for films like _Silent Running_, _The Wild Party_, and _At the Earth's Core_. His book _Lil Dan’l: One year in a Relocation Center_ recognizes the Japanese American struggle in the concentration camps.

**Comment by Prot0ast** [comment]
<i> done </i>
