### ISSUE TITLE
[Acknowledge ][Acknowledgement should be remembrance, Words run away]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#103]
### Acknowledge 
Acknowledgement page should be called remembrance, perhaps double column format to fit words

### What We Should Do to Fix it
- [x] Replace Acknowledgement title with remembrance title
- [x]  perhaps double column format to fit words

### Copy And Paste-able Text
Remembrance

**Comment by Prot0ast** [comment]
double column works
