### ISSUE TITLE
[Marie Mizutani - Yearbook][text is wrongish]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#104]
### *Marie Mizutani - Yearbook*
*space needed between , and Marie*

### What We Should Do to Fix it
- [x] copy paste below text

### Copy And Paste-able Text
Marie Mizutani, from Walnut Grove, was sent to the Merced Assembly Center, away from her Stockton classmates, and then to the Amache Concentration Camp in Colorado. On leave from Amache in 1945, Marie worked in Detroit as a city clerk. She then enrolled at Colorado State College for Education. After the war, Marie moved to Oakland, California where she directed the choir for West Tenth Methodist Church.

**Comment by Prot0ast** [comment]
lol
