### ISSUE TITLE
[Camp Rohwer Remains][Audio continues]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#107]
### Camp Rohwer Remains
*The Before section music (Any music really) plays over the page if you use the drop down menu in the before section to jump to the war is over.*

### What We Should Do to Fix it
- [x] Have a check that unplays whatever the music was?

**Comment by Prot0ast** [comment]
adjusted the change scene script to reflect these changes so that now the war is over button jumps to the splash page for the war is over instead. the bug can now no longer be replicated (I hope 🤞)
