### ISSUE TITLE
[Redress][Providing a citation for the video]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#119]
### *Redress
*The video itself has citation and may lose it after the video change.*

### What We Should Do to Fix it
- [ ] *insert Courtesy Ronald Reagan Presidential Library below the video when it is implemented.*

### Copy And Paste-able Text
Courtesy Ronald Reagan Presidential Library

**Comment by Prot0ast** [comment]
@KGTrammel you need to update this issue with the current plan of action being to add a slideshow instead while the .mp3 plays in the background since we are omitting the utilization of the .mp4
