### ISSUE TITLE
[Redress and Yearbook][Can we swap their positions?]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#123]
### *Redress and Yearbook*
*Our newest draft decided to play redress before we go into the student yearbook.  Its a low priority at this point but can we swap their positions?*

### What We Should Do to Fix it
- [ ] *swap the positions of redress and yearbook*

**Comment by Prot0ast** [comment]
@KGTrammel prolly going to bring this up with everyone tmw

**Comment by cfines** [comment]
dropped
