### ISSUE TITLE
[New Page - Right after main][Explain Branching path structure]

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#126]
Some users might not be familiar with the branching path style that the app uses.  A brief bit of text before starting the story explaining what a branching path app is, and how they can go back an experience the different parts.

**Comment by Prot0ast** [comment]
@CCrawfordUOP would adding this kind of information onto the context page work?

**Comment by CCrawfordUOP** [comment]
Added to #128
