### ISSUE TITLE
[Multiple Pages - Audio][Add fade in/out on page changes that trigger new track to play]

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#127]
Some of the pages that trigger audio loops can cause an abrupt change in the sound.  Low priority, but adding a fade out/fade in on pages that trigger new music loops would be a nice small QOL change.

**Comment by Prot0ast** [comment]
- [ ] *adding method to fade audio out gradually*

**Comment by Prot0ast** [comment]
https://johnleonardfrench.com/how-to-fade-audio-in-unity-i-tested-every-method-this-ones-the-best/ <- current resource

**Comment by Prot0ast** [comment]
@CCrawfordUOP I have a script called FadeAudio.cs in the audio_implementation branch where I've begun implementing this. It takes a method from the ContinueAudio.cs to run the Coroutine.

**Comment by Prot0ast** [comment]
@CCrawfordUOP I have figured out how to do this by initializing the audio source with a clip on start with a separate script, then adding a 3 line if check that sees if the suggested new track is different than the one that is currently preloaded. I'll be making changes to scenes where I force audio to start anew.
