### ISSUE TITLE
[Loyalty Test][Yes/No Switches Rework]

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#129]
Current yes/no switches are a bit confusing.  Investigating alternative options could improve usability.

**Comment by Prot0ast** [comment]
tysm

**Comment by CCrawfordUOP** [comment]
Changes made in my branch, will merge tomorrow.

**Comment by Prot0ast** [comment]
I reviewed the changes in the branch and went ahead and merged them onto the current branch. Thank you very much for helping us out with this.
