### ISSUE TITLE
[Japanese Club][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#131]
### *Japanese Club (and respective students*
*button text is wrong now*

### What We Should Do to Fix it
- [x] change Japanese Club buttons
- [x] change Student buttons for each chosen student

### Copy And Paste-able Text
Approach...
James, talking with friends?
Grayce, playing piano?
Marie, putting up posters?

NEXT
Approach...
James: Mary, Jimmie's friend?
Grayce: Toshio and Kei, Grayce's siblings?
Marie:  George, historian and cartoonist?

**Comment by Prot0ast** [comment]
gonna put this on hold till we get marie's input

**Comment by cfines** [comment]
its done, though i think it kinda messes with the consistency, tho we'll talk about it more tomorrow.

**Comment by cfines** [comment]
oops didnt mean to close

**Comment by cfines** [comment]
looks like nobody had any complaints during the presentation on this, ill close it now.
