### ISSUE TITLE
[Education][Nisei and Issei are mentioned without a definition ]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#149]
### *Education*
*Nisei and Issei are mentioned without a definition*

### What We Should Do to Fix it
- [x] *Replace the text with the modified below text*

### Copy And Paste-able Text
College educated adults, including Richard Doi and Hiroshi Uyehara (Grayce’s future husband), teach primary school in makeshift classrooms. Students sit on wooden benches and teachers make do. For some young adults whose college journeys have been interrupted, the National Japanese American Student Relocation Committee helps them attend colleges outside the military zone. Other adults—primarily older adults—take classes in English and traditional Japanese arts and crafts.

**Comment by cfines** [comment]
yeh
