### ISSUE TITLE
[Yearbook][Text Changes for Toshio and Marie]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#166]
### *Yearbook*
*Text Changes for Toshio and Marie since we updated the text*

### What We Should Do to Fix it
- [x] *Replace landscaper with music teacher in Toshio's bio*
- [x] *Add to the end of Toshio's text box: Pacific awarded him a Bachelor of Music degree, posthumous honoris causa in 2012.*
- [x] *Add to the end of Marie's bio: She was awarded a Bachelor of Music degree, posthumous honoris causa from Pacific in 2012.*

### Copy And Paste-able Text
music teacher 
Pacific awarded him a Bachelor of Music degree, posthumous honoris causa in 2012.

She was awarded a Bachelor of Music degree, posthumous honoris causa from Pacific in 2012.*

**Comment by cfines** [comment]
yeh
