### ISSUE TITLE
Final Polish

### ISSUE THREAD

**Issue by CCrawfordUOP** [uop-libraries/CreativeResponse2022#198]
- [x] Update text on credits page - remove "*accessible on YouTube"
- [x] Expand dropdown menu to include credits
- [x] Add credits page button to options page
- [x] Fix app homescreen icon

**Comment by CCrawfordUOP** [comment]
I think these are the last things needed before app store submission.  I'll take care of fixing the homescreen icon.

**Comment by Prot0ast** [comment]
Updated everything except the homescreen icon

**Comment by CCrawfordUOP** [comment]
New app icon in place and working on iOS and Android.
