### ISSUE TITLE
Context page text fix plz

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#70]
- wrong text for "context" page
- On December 7, 1941 Japan attacked Pearl Harbor, escalating pre-existing racist views towards Japanese immigrants and Japanese American citizens. The “yellow peril” concept, accusing Japanese Americans of threatening the “white race”, led to restrictive immigration, naturalization, and property ownership laws. On February 19, 1942, Executive Order 9066 tore 122,000 Japanese Americans, including 55 Pacific students, from the lives they knew. Their stories enlighten us about this tragedy and the strength needed to endure it.

**Comment by cfines** [comment]
yuh
