### ISSUE TITLE
[Mary Yamashita][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#76]
### *Mary Yamashita*
*typo*

### What We Should Do to Fix it
- [x] *copy paste text below*
- [x] it's kinda imperative that the Pacific Weekly part gets italicized

### Copy And Paste-able Text
Mary, a Stockton Junior College student, reports and edits for the _Pacific Weekly_ newspaper too. She and Jimmie met in study hall at Stockton High and use the club meetings to catch up. Mary plans to pursue an English degree and Jimmie will go to Berkeley for his PhD.

**Comment by cfines** [comment]
done'd
