### ISSUE TITLE
[Marie Mizutani][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#77]
### *Marie Mizutani*
*typo*

### What We Should Do to Fix it
- [x] copy paste text
- [ ] is imperative that you make sure Pacific Weekly is italicized

### Copy And Paste-able Text
Marie, the dance committee organizer, puts down the posters and thanks George Akimoto, club historian and _Pacific Weekly_ cartoonist, for advertising the dance. Marie’s from Walnut Grove, a close-knit Japanese American agricultural community in the San Joaquin Delta. Her efforts on the committee build a closer Pacific community.

**Comment by cfines** [comment]
lasdkjgnlsdkjgblkdfjbsn when push comes to shove i will italicize
