### ISSUE TITLE
Design Edits - Title & Context Page

### ISSUE THREAD

**Issue by tnanhx** [uop-libraries/CreativeResponse2022#78]
**Title Screen:** 
- [x] Replace placeholder buttons with the long white buttons located in the Teams folder (UI Stuff) 
- [x] Edit the borders so they're more thin [(see Miro board for reference)](https://miro.com/app/board/uXjVPeeLlfY=/)
- [x] Slide the buttons down a bit

**Context Page:**
- [x] Rename context to "Prelude" and slide the text closer to the left margin (same margin as body paragraph)
- [x] Change the dark button to the short white button and properly scale it
- [x] Transition: Fade to black from Prelude to Japanese Club (Missing cover page for Japanese Club btw) 

Idk how to format it so i'll just go by screens/pages

**Comment by cfines** [comment]
done, same as how pacific weekly is set up.
