### ISSUE TITLE
Design Edits - Japanese Club

### ISSUE THREAD

**Issue by tnanhx** [uop-libraries/CreativeResponse2022#79]
**Japanese Club Cover:**
- [x] It's missing, please add if possible? :o [(Mirooo)](https://miro.com/app/board/uXjVPeeLlfY=/)
- [x] Scale borders so theres more room at the sides and tops

**Interaction Pages:**
- [x] If possible, please change the blue choice buttons to the same color as text or use just a black button (Ik marie did that but it doesn't work here in my opinion) Open for thoughts otherwise though 
- [x] Scale borders so theres more room at the sides and tops

**Bio Pages:**
- [x] Replace ugly wiggly line with the straight line in Teams folder pls 😺 emotes wow 🪱 
- [x] For bio pages only, make the header (names) centered underneath the portraits rather than on top
- [x] Scale borders so theres more room at the sides and tops

Note: These are just some things that can be changed now, I'll just talk to you guys tomorrow about specifics

**Comment by cfines** [comment]
everything should be done now, we'll check with you tomorrow
