### ISSUE TITLE
Ending of App

### ISSUE THREAD

**Issue by tnanhx** [uop-libraries/CreativeResponse2022#81]
Note: Instead of ending the app on credits, move the credits to a button in the settings menu. That way it isn't forced onto the viewer but rather they have a choice to see who worked on the project 

**In rememberance/Acknowledgements:**
- [x] Transition to fade to black rather than end on credits
- [x] Maybe use lantern animation or image of our logo to end instead

**Credits:**
- [x] Move credits to settings page

**Comment by Prot0ast** [comment]
@tnanhx would you suggest changing the continue button text then to say end? then have it just return to the title screen?

**Comment by tnanhx** [comment]
> @tnanhx would you suggest changing the continue button text then to say end? then have it just return to the title screen?

We can scrap this idea, Lisa told me it can still work having the Rememberance > Lanterns/Logo > Credits; just as long as we make the credits scene a little different. I think that can be achieved by removing the secondary BG and changing the BG color so its darker :0 (maybe the same hex as warning page)

**Comment by Prot0ast** [comment]
credits has been moved to dropdown for each prefab
