### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by tnanhx** [uop-libraries/CreativeResponse2022#83]
All body texts/paragraphs should be left aligned and not centered. Marie will prob freak out and die if not fixed. Also applies for **most** headings/subheadings. Only bio pages (ones with names an portraits should be centered below the portrait)

Margins of all text and photos should have the same distance. 

**How to fix?**
- [x] Left align paragraphs (applies for all texts except name headings)
- [x] Move bio name headings so that they are below the portrait rather than on top
- [x] Align even margins

**Comment by cfines** [comment]
Before and During sections are done, all that's left is the After section which is after Alan is done with his audio issues. Marking as done cause it will be over soon.
