### ISSUE TITLE
[Goodbye Assembly Center][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#86]
### *Goodbye Assembly Center*
*not the pacific students but the incarcerees*

### What We Should Do to Fix it
- [x] *copy and paste text below*

### Copy And Paste-able Text
After five months of incarceration, the Japanese Americans held at the Stockton Fairgrounds Assembly Center are being moved to permanent camps. Rohwer, Arkansas is the destination for the incarcerees.

**Comment by Prot0ast** [comment]
text updated, also had to resize because it made an orphan
