### ISSUE TITLE
[Rohwer Outpost All three pages] [Adding text]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#87]
### Rohwer Outpost New Medics Here, Agriculture is Successful, and Indefinite Leave
Lacks an issue number and date of publishing probably cause I forgot to give you one.

### What We Should Do to Fix it
- [x] Add the first missing text below the main block of the first page
- [x] Add the second missing text below the main block of the second page
- [ ] Add the third missing text below the main block of the third page

### Copy And Paste-able Text
1. *The Rohwer Outpost,  Vol. lll No. 36  November 3, 1943* Italics
2. *The Rohwer Outpost,  Vol. lll. No. 23 September 18. 1943*
3.  *The Rohwer Outpost, Relocation Bullentin April 13, 1943*

**Comment by Prot0ast** [comment]
lol

**Comment by Prot0ast** [comment]
I'm going to assume you wanted italics for all of them, also this is completed :)
