### ISSUE TITLE
[Redress][Now a slideshow]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#91]
### Redress
The Ronald Reagan signing video is full of alot of extra material

### What We Should Do to Fix it
- [ ] A member of the team (probably not the developers) edits together audio from the youtube for use on the app.
- [x] Use Redress image one, Redress image two, and Redress image three from the redress section of finalized visuals to create a three image slideshow in place of the video.
- [x] insert Courtesy Ronald Reagan Presidential Library below the slideshow when it is implemented.

Copy And Paste-able Text
Courtesy Ronald Reagan Presidential Library

**Comment by Prot0ast** [comment]
@KGTrammel I need you to be more specific about these photos in the after section. Which ones would you want me to include exactly?

**Comment by Prot0ast** [comment]
@CCrawfordUOP I would really appreciate your input on this issue as there are two methods that can be utilized for this to be added. Either the background music gets swapped out with the audio track of redress (which makes it subjective to choppiness when switching scenes) or adding another separate audio source (which might throw more errors with having another audio listener present).

**Comment by Prot0ast** [comment]
awaiting changes to audio scripts

**Comment by Prot0ast** [comment]
@KGTrammel I need the audio for this to be a lot louder
