### ISSUE TITLE
[Recreational Distractions][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#92]
### *Recreational Distractions*
*text is not updated*

### What We Should Do to Fix it
- [x] copy paste part below

### Copy And Paste-able Text
During the sports season dirt fields are smoothed and teams for football, baseball, and basketball share scarce equipment. There are public halls for Buddhist, Catholic, and Protestant services. Children can join Boy Scouts and Girl Scouts to learn outdoor and camping skills. Some adults gamble with cards (hanafuda or standard western) and mahjong to pass time.

**Comment by Prot0ast** [comment]
copy and pasted :)
