### ISSUE TITLE
[Education][text is wrong]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#94]
### *Education*
*text is wrong*

### What We Should Do to Fix it
- [x] copy paste the text below

### Copy And Paste-able Text
Educated Nisei, including Richard Doi and Hiroshi Uyehara (Grayce’s future husband), teach primary school in makeshift classrooms. Students sit on wooden benches and teachers make do. For some young adults whose college journeys have been interrupted, the National Japanese American Student Relocation Committee helps them attend colleges outside the military zone. Other adults—primarily Issei—take classes in English and traditional Japanese arts and crafts.

**Comment by Prot0ast** [comment]
ctrl + c & ctrl + v'd
