### ISSUE TITLE
[The War is over][The music loops too soon]

### ISSUE THREAD

**Issue by KGTrammel** [uop-libraries/CreativeResponse2022#95]
### The war is over to Yearbook
The music loops much too soon during the yearbook section

### What We Should Do to Fix it
- [x] Edit a longer music track for the war is over page
- [x] Insert the longer music track in the place of the old war is over music.

**Comment by Prot0ast** [comment]
waiting on new audio clip from @DomRest3

**Comment by CCrawfordUOP** [comment]
New track received and added to project.
