### ISSUE TITLE
[Camp Rohwer Remains][text is wrongish]

### ISSUE THREAD

**Issue by keiwong57** [uop-libraries/CreativeResponse2022#98]
### *Camp Rohwer Remains*
*end of the paragraph is missing a period and there's a widow and orphan child thing?*

### What We Should Do to Fix it
- [x] add period after "new lives"
- [x] change text size or spacing so that "new lives" isn't by itself
- [x] retitle to Last Days at Rohwer

**Comment by Prot0ast** [comment]
suggestions implemented
